version: '2'
services:
  harbor-setupwrapper:
    image: mreferre/harbor-setupwrapper
    container_name: harbor-setupwrapper
    environment:
      - HARBORHOSTNAME='pod4.vmug.it'
      - HARBOR_ADMIN_PASSWORD='Vmware123!'
    volumes:
      - /etc/registry
      - /etc/ui
      - /etc/jobservice
      - /etc/nginx
      - /configdb
      - /configui
      - /configjobservice
    command: /harbor/harbor-setupwrapper.sh

  log:
    image: vmware/harbor-log:0.5.0
    container_name: harbor-log
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/
    ports:
      - 1514:514

  registry:
    image: library/registry:2.5.0
    container_name: registry
    restart: always
    volumes:
      - /data/registry:/storage
    volumes_from:
      - harbor-setupwrapper
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"

  mysql:
    image: vmware/harbor-db:0.5.0
    container_name: harbor-db
    restart: always
    volumes:
      - /data/database:/var/lib/mysql
    volumes_from:
      - harbor-setupwrapper
    depends_on:
      - log
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
    entrypoint: "/bin/sh -c"
    command: "/configdb/entrypointdb.sh"

  ui:
    image: vmware/harbor-ui:0.5.0
    container_name: harbor-ui
    restart: always
    volumes:
      - /data:/harbor_storage
    volumes_from:
      - harbor-setupwrapper
    depends_on:
      - log
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
    entrypoint: /configui/entrypointui.sh

  jobservice:
    image: vmware/harbor-jobservice:0.5.0
    container_name: harbor-jobservice
    restart: always
    volumes:
      - /data/job_logs:/var/log/jobs
    volumes_from:
      - harbor-setupwrapper
    depends_on:
      - ui
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
    entrypoint: /configjobservice/entrypointjobservice.sh

  proxy:
    image: nginx:1.11.5
    container_name: nginx
    restart: always
    volumes_from:
      - harbor-setupwrapper
    ports:
      - 80:80
      - 443:443
    depends_on:
      - harbor-setupwrapper
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
